### ISSUE TITLE
Bad accessions kill the API

### ISSUE THREAD

**Issue by ewels** [seqeralabs/ffq-api#6]
Looks like `ffq` calls `sys.exit(1)` quite a lot when it hits errors. This needs some refactoring to raise exceptions to the CLI function instead, so that we can capture them and handle them nicely.

**Comment by pditommaso** [comment]
Pending a new release including https://github.com/pachterlab/ffq/pull/31

**Comment by pditommaso** [comment]
It looks like both this and #3 have been solved. Should this project be resurrected?

**Comment by bentsherman** [comment]
Resolved by #11
